### PR TITLE
test: add fuzz testing for checker, with fixes

### LINKED ISSUE #1110: Enhance differential fuzz tests to run the checker after completing
The checker should be used after running the differential fuzz tests, both in ethhash and non-ethhash cases.

### PR DESCRIPTION
**Pull request by rkuris**
Fixes #1110

Passes consistently with the following fixes:
 - The partial path for the branch was not added when computing the child hashes
 - Always render the path, not the partial path before this node

### CODE REVIEW

File: storage/src/checker/mod.rs [hunk 1]
```diff
@@ -374,12 +377,12 @@ mod test {
         err,
         CheckerError::HashMismatch {
             address,
-            partial_path,
+            path,
```
Comment (rkuris) [inline storage/src/checker/mod.rs:387]: Debugging this would have been easier if we constructed the error and used assert_eq! on them, as the debug output would highlight the difference.

File: firewood/src/db.rs [hunk 2]
```diff
@@ -767,6 +778,48 @@ mod test {
...
+                let value: [u8; 32] = rng.borrow_mut().random();
+                batch.push(BatchOp::Put { key, value });
+                trace!("batch: {batch:?}");
+                batch
+            });
+            let proposal = db.propose(batch).await.unwrap();
+            proposal.commit().await.unwrap();
+
+            // check the database for consistency, sometimes checking the hashes
+            let hash_check = rng.borrow_mut().random();
```
Comment (qusuyan) [inline firewood/src/db.rs:815]: I think we should just always check the hashes - I don't expect the checker to do any more when hash_check is false

File: storage/src/checker/mod.rs [hunk 3]
```diff
@@ -111,8 +112,10 @@ impl<S: WritableStorage> NodeStore<Committed, S> {
         if hash_check {
             let hash = hash_node(&node, &path_prefix);
             if hash != subtree_root_hash {
+                let mut path = path_prefix.clone();
```
Comment (qusuyan) [inline storage/src/checker/mod.rs:122]: we probably don't need the extra clone()

File: storage/src/checker/mod.rs [hunk 4]
```diff
@@ -278,7 +281,7 @@ mod test {
             value: Box::new([3, 4, 5]),
         });
         let leaf_addr = LinearAddress::new(high_watermark).unwrap();
-        let leaf_hash = hash_node(&leaf, &Path::from_nibbles_iterator([0u8, 1].into_iter()));
+        let leaf_hash = hash_node(&leaf, &Path::from_nibbles_iterator([0u8, 0, 1].into_iter()));
```
Comment (qusuyan) [inline storage/src/checker/mod.rs:291]: Seems that I have constantly mistaken what partial path really means. Thanks for pointing this out!

File: firewood/src/db.rs (hunk 2 above)
Comment (rkuris) [reply firewood/src/db.rs:815]: Let's check both paths by disabling it sometimes. It might run a little faster too, giving us more fuzzing.

File: storage/src/checker/mod.rs [hunk 5]
```diff
@@ -256,41 +259,44 @@ mod test {
...
     // -------------------------
+    // | partial path: []      |
     // |     |  X  |  X  | ... |    Root node
     // -------------------------
     //    |
     //    V
     // -------------------------
-    // |  X  |     |  X  | ... |    Branch node
+    // | partial path: [9]     |
+    // |  X  |     |  X  | ... |    Branch node (path: 0x09)
```
Comment (rkuris) [inline storage/src/checker/mod.rs]: Why are we changing this in this PR?

This feels really random. Is that the intention?

Seems like having something more orthogonal would make understanding this structure a bit easier going forward.
